import { Roboto } from 'next/font/google';
import classNames from 'classnames';
import { UserConfigProvider } from './context/userConfig';
import Header from './components/Header';
import Footer from './components/Footer';
import Background from './components/Background';
import './globals.scss';
import styles from './layout.module.scss';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["300", "500", "900"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const layoutClasses = classNames(roboto.className, styles.layout);

  return (
    <html lang="en">
      <body className={layoutClasses}>
        <UserConfigProvider>
          <Header />
          <main className={styles.layout__main}>
          {children}
          </main>
          <Footer />
          <Background />
        </UserConfigProvider>
      </body>
    </html>
  );
}
